os: linux
dist: focal
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - '3.9-dev'
  
install:
  - make deps-pip deps-pip-test assets > /dev/null
  - pip install flake8
script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - make test
